// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFilesInfo(arg1:Array<string>):Promise<Array<main.FileInfo>>;

export function GetImageData(arg1:string):Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SetIndividualFileTimes(arg1:Array<main.FileTimestamp>):Promise<void>;
