// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilesInfo(arg1) {
  return window['go']['main']['App']['GetFilesInfo'](arg1);
}

export function GetImageData(arg1) {
  return window['go']['main']['App']['GetImageData'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SetIndividualFileTimes(arg1) {
  return window['go']['main']['App']['SetIndividualFileTimes'](arg1);
}
